import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import NavBar from "@/components/navBar";
import Hero from "@/components/Hero";
import MovieList from "@/components/MovieList";
import SearchList from "@/components/SearchList";
import useMovieStore from "@/store";

const inter = Inter({ subsets: ["latin"] });

export default function Search({ data, query, page, total }) {
  const [items, setItems] = useState(data ? data.cast : null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <NavBar />

      {/* Hero */}
      <Hero />

      {/* Movie list cards */}
      <SearchList items={items} query={query} page={page} total={total} />
    </>
  );
}

export async function getServerSideProps({ query, resolvedUrl }) {
  const res = await fetch(
    `https://api.themoviedb.org/3/search/person?query=${query.query}&api_key=${process.env.API_KEY}`
  );
  const data = await res.json();

  if(data.results <= 0){
    return {
        props: {
          data: null,
          query: query.query,
          page: query.page,
          total: 0,
        },
      };
  }
  else{
  const movies =
    parseInt(query.page) > 1
      ? await fetch(
          `https://api.themoviedb.org/3/person/${data.results[0].id}/movie_credits?api_key=${process.env.API_KEY}&page=${query.page}`
        )
      : await fetch(
          `https://api.themoviedb.org/3/person/${data.results[0].id}/movie_credits?api_key=${process.env.API_KEY}&page=1`
        );
  const resp = await movies.json();

  return {
    props: {
      data: resp,
      query: query.query,
      page: query.page,
      total: resp.cast.length,
    },
  };
}
}
